### ISSUE TITLE
Enhancements to dogears?

### ISSUE THREAD

**Issue by alphapapa** [gitrj95/breadcrumbs.el#1]
Hi,

I saw your post on emacs-devel about this package.  It looks like you've done a good job.

Of course, you're free to make your own tools to scratch your own itches.  But I saw this part of the readme:

> [dogears](https://github.com/alphapapa/dogears.el) or [gumshoe](https://github.com/Overdr0ne/gumshoe): both of these packages are great, and this package is largely inspired by the two of these. however, i, personally, have no interest in using either time or distance as a signal for tracking positions. i am principally interested in:
> 
>     support for position tracking in live and killed buffers
>     support for persisting the list of tracked positions between emacs sessions
>     well-defined navigation
>     allowing arbitrary functions to track the before and after positions around the call

And I wonder if Dogears could be enhanced to meet these needs.  For example, the `dogears-functions` option lets you choose functions to be advised to remember a place when they are called.  And according to https://github.com/alphapapa/dogears.el/issues/4, `savehist` can be used to persist the `dogears-list` between sessions.  Dogears already tracks positions in killed buffers by way of using Emacs bookmarks internally (so if the buffer's major mode has a `bookmark-make-record-function`, it can be recreated by Dogears after being killed).  

And as for well-defined navigation: well, I see that you made this PR a while back: https://github.com/alphapapa/dogears.el/pull/19  Apologies for overlooking it; it's been a busy year so far.  FWIW, I just pushed some improvements to Dogears that you might find interesting.  For example, the commands to remember a place and move forward/back take a prefix argument to only consider manually remembered places; so you can easily "dogear" or "drop a breadcrumb" at a place that's significant, and move between such places without having to go through all of the automatically remembered places too.

Anyway, I do, of course, wish you luck with your own package.  But if Dogears could be made to suit your needs better, please let me know.  I feel like Dogears isn't fulfilling its potential yet, and feedback from users could help.

**Comment by gitrj95** [comment]
hi! i admire your work! thanks for taking the time to respond :)

wrt enhancing dogears to satisfy my personal requirements, i certainly have np doing this (provided i have the time). a few things:
- another thing i didn't mention in the readme that i probably should, is that ring semantics are of value to my workflow
- i wrestled a bit with using bookmarks internally, but i figured since i didn't have a use case for keeping them with the rest of the bookmarks, the only advantage was the one you suggested, but, i am not sure how packages will actually operate. the onus is on them, iirc, but my personal workflow would involve something like, eg a python buffer that has built up some state, and this state doesn't seem like something that could be reconstituted by packages, generally, and such buffers typically have no guards around being closed. at least with file-backed buffers, emacs by default will warn you if you try to close them, right? at least, that's the ethos i used
- i also want to go through this process end-to-end with deployment to elpa, because i have some other ideas that are less simple to implement and i wanted to be familiar with the process. figured it was easiest to start with a simple package like this one

**Comment by alphapapa** [comment]
> hi! i admire your work! thanks for taking the time to respond :)

Thanks.
> 
> wrt enhancing dogears to satisfy my personal requirements, i certainly have np doing this (provided i have the time). a few things:

To be clear, I didn't mean that you should necessarily implement those enhancements yourself.  I was wondering if your needs could be met if Dogears were suitably enhanced.
> 
>     * another thing i didn't mention in the readme that i probably should, is that ring semantics are of value to my workflow

I've no objection to implementing `dogears-list` as a ring or with such semantics.  Whether to stop at an end of the list or cycle around could be an option.

> 
>     * i wrestled a bit with using bookmarks internally, but i figured since i didn't have a use case for keeping them with the rest of the bookmarks, the only advantage was the one you suggested, but, i am not sure how packages will actually operate. the onus is on them, iirc, but my personal workflow would involve something like, eg a python buffer that has built up some state, and this state doesn't seem like something that could be reconstituted by packages, generally, and such buffers typically have no guards around being closed. at least with file-backed buffers, emacs by default will warn you if you try to close them, right? at least, that's the ethos i used

It's up to a major mode to implement a `bookmark-make-record-function`, otherwise the buffer is restored by name, if one by that name exists.

> 
>     * i also want to go through this process end-to-end with deployment to elpa, because i have some other ideas that are less simple to implement and i wanted to be familiar with the process. figured it was easiest to start with a simple package like this one

Understandable, but please consider that ELPA's purpose is not to be a training ground for new Elisp developers.  ELPA exists to host packages that are useful to Emacs users.  The package-submission process is orthogonal to the development of the useful functionality of a library.  So if you have ideas for other libraries or tools, you should work on them, and when they're ready, submit them as packages.  Then the ELPA maintainers will help you with the process as needed.  In other words, you needn't "practice" by submitting simple libraries to ELPA first.  Go ahead and work on the "serious" ones, and then submit them when ready, or ask for help as needed during the development process.

**Comment by gitrj95** [comment]
> To be clear, I didn't mean that you should necessarily implement those enhancements yourself. I was wondering if your needs could be met if Dogears were suitably enhanced.

noted. but dogears has a ton of features that i don't particularly need, and it has an interface not entirely aligned with my particular preferences. i agree the packages are not disjoint, but i don't think increasing the scope or changing the semantics of your package to meet the needs of mine is, in general, a good idea. in your own pr's you cite that you originally never intended for persistence of dogears, for example, and you explicitly do not support ring semantics, presumably for good reason. adding the additional knobs i think is less preferable to having two separate packages with specific ethos. at least, that's my personal taste

> It's up to a major mode to implement a bookmark-make-record-function, otherwise the buffer is restored by name, if one by that name exists.

yes, i understand, but i intentionally do not want to support this because i can't think of a scenario where this property would be useful to my workflow. eg, in the case above, presumably (i have not checked the implementation), it would either restore the python buffer with no interpreter state and point would jump to whatever position was "tracked" that no longer exists, which is not useful, or fail to restore, which is not useful either

> Understandable, but please consider that ELPA's purpose is not to be a training ground for new Elisp developers ...

yes, i understand. that isn't my intent. the "practice" you are referring to is simply learning what is required to submit a package and what that process is, what conventions/idioms are preferred by elpa maintainers, etc. knowing that good citizenry is reasonable, imo, a priori to working on a more complex project, when such rework would constitute a larger job

**Comment by alphapapa** [comment]
> noted. but dogears has a ton of features that i don't particularly need, and it has an interface not entirely aligned with my particular preferences. i agree the packages are not disjoint, but i don't think increasing the scope or changing the semantics of your package to meet the needs of mine is, in general, a good idea.

I'm not sure what you mean.  Dogears doesn't have very many features at all.  :)

>  in your own pr's you cite that you originally never intended for persistence of dogears, for example, 

Right, but it's not even necessary to do so, because `savehist` can take care of that itself.

> and you explicitly do not support ring semantics, presumably for good reason. 

I'm not sure what you mean; I just said that I have no objection to using ring semantics or data structures.

> adding the additional knobs i think is less preferable to having two separate packages with specific ethos. at least, that's my personal taste

That can be preferable sometimes, yes.

> yes, i understand, but i intentionally do not want to support this because i can't think of a scenario where this property would be useful to my workflow. eg, in the case above, presumably (i have not checked the implementation), it would either restore the python buffer with no interpreter state and point would jump to whatever position was "tracked" that no longer exists, which is not useful, or fail to restore, which is not useful either

comint or other interpreter buffers are a notable exception, yes.  But what does `breadcrumbs` do differently with them?

> yes, i understand. that isn't my intent. the "practice" you are referring to is simply learning what is required to submit a package and what that process is, what conventions/idioms are preferred by elpa maintainers, etc. knowing that good citizenry is reasonable, imo, a priori to working on a more complex project, when such rework would constitute a larger job

The process, conventions, idioms, and expectations are documented in the ELPA documentation, the Elisp manual (see the appendix on conventions), the MELPA guidelines, and https://github.com/alphapapa/emacs-package-dev-handbook  So if you have questions about them, it would be good to ask them on the mailing list and improve the documentation.  The idea is to have answers to those questions available in advance of authors submitting packages, rather than authors having to learn by submitting and going back-and-forth with maintainers.  

You could also review prior submissions on the mailing list to see what feedback other authors have been given.

To submit a package for the sake of going through the exercise of submitting a package wouldn't be fair to the ELPA maintainers, who are busy enough already.  I'm not sure if this is what you meant that you're doing.  Anyway, my point is that you should be able to learn everything you need to know by the existing documentation and examples, before you submit a package "for real."  :)

**Comment by gitrj95** [comment]
> I'm not sure what you mean; I just said that I have no objection to using ring semantics or data structures.

i'm referring to the code. having a notion of a "front" and a "back" with no wrap also seems useful

> comint or other interpreter buffers are a notable exception, yes. But what does breadcrumbs do differently with them?

i explicitly don't support opening their tracked positions if the buffer is closed, is what i mean

> The process, conventions, idioms, and expectations are documented in the ELPA documentation, the Elisp manual (see the appendix on conventions), the MELPA guidelines, and https://github.com/alphapapa/emacs-package-dev-handbook 

i didn't see anything about idioms, design patterns, and the like in the elpa documentation. didn't look in the other places. that repo you've linked is great! thanks

> I'm not sure if this is what you meant that you're doing

no, i find the package useful, and i've been using it for a while locally as there was nothing that satisfied my particular use cases at the time. i just figured i should publish it, and in doing so get acclimated to the process

> general

thanks! the emacs community is very encouraging and helpful, and development seems very active for such a mature editor. i'll close this thread, but i'll certainly pick your brain on future work :)
